name: Maven build workflow

jobs:
  build:
    name: Dowload required artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Java setup
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Download artifacts
        run: mvn clean initialize
 
